// <auto-generated />
namespace FacebookBucketList.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class completed_not_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(completed_not_required));
        
        string IMigrationMetadata.Id
        {
            get { return "201301012256178_completed_not_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
