// <auto-generated />
namespace FacebookBucketList.Core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class relations_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relations_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201301012248114_relations_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
